### ISSUE TITLE
Незначительный баг верстки на экране с пользователями

### ISSUE THREAD

**Issue by Anna-Prokhorova** [KristinaKac/meetup_2#1]
Если строку перевести в режим редактирования между кнопками пропадает gap

![image](https://github.com/KristinaKac/meetup_2/assets/59168625/0b9d27bb-7bb2-4130-bea5-dee8197ff2ff)

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/22f1fdf8c0050f783dc0d1bd024d3019685d2c4f
