### ISSUE TITLE
Маленький стейт в отдельном файле

### ISSUE THREAD

**Issue by Anna-Prokhorova** [KristinaKac/meetup_2#10]
Я могу понять почему так сделано и это абсолютно имеет право на жизнь, но блин стейт слишком маленький))
В нем всего два поля и выносить его в отдельный файл как-то ну совсем ту мач. Обычно сам начальный стейт указываем в файле с редьюсером, а вот интерфейс для этого начального стейта действительно можно и стоит вынести отдельно.
Выносить сам начальный стейт в отдельный файл (а интерфейс для него в еще один отдельный файл) наверно круто, если он огромный типо 20+ полей или там большая вложенность и т.д.
https://github.com/KristinaKac/meetup_2/blob/fb63bf38da7be6b2f7eabf86d32f81b48ab344c0/src/app/modules/user/store/user.state.ts#L1-L12

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/f7f15cbac6213fddb2d79f2f9f0e5219636abc18
