### ISSUE TITLE
Типы экшенов можно выносить в enam

### ISSUE THREAD

**Issue by Anna-Prokhorova** [KristinaKac/meetup_2#11]
Просто совет выносить типы экшенов в инам, который указывается вверху.
При жесткой типизации файл с экшенами превращается в жесткий boilerplate и полезно иметь сверху такой инам как некое содержание или список экшенов и их типов
https://github.com/KristinaKac/meetup_2/blob/fb63bf38da7be6b2f7eabf86d32f81b48ab344c0/src/app/modules/user/store/user.actions.ts#L1-L39

Пример boilerplate:
![image](https://github.com/daniilkiselev97/meetups-project/assets/59168625/ebb25643-cb05-43ea-9516-061432b265ac)

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/13ba3aadb6b251ef2b24ef28045f9ffa9c2efa7e
