### ISSUE TITLE
Можно ознакомиться с оптимальным паттерном регистрирования призмовских иконок

### ISSUE THREAD

**Issue by Anna-Prokhorova** [KristinaKac/meetup_2#12]
У Призмы есть проблема, что надо постоянно регистрировать иконки для каждого компонента отдельно, хотя многие из них на самом деле переиспользуются среди компонентов.
В нашей команде выработался паттерн для того чтобы эту проблему контрить.
Если вкратце, то регистратор иконок выносится в отдельный модуль, который будет располагаться в shared папке, а дальше там где надо импортим этот модуль.
Посмотреть пример такого модуля можно тут (пункт про регистрацию иконок): [https://kb-liga.phoenixit.ru/pages/viewpage.action?pageId=279427968#id-ВнедрениеNx-Частовстречающиесякейсыипредложенияпоихреализации](https://kb-liga.phoenixit.ru/pages/viewpage.action?pageId=279427968#id-%D0%92%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BD%D0%B8%D0%B5Nx-%D0%A7%D0%B0%D1%81%D1%82%D0%BE%D0%B2%D1%81%D1%82%D1%80%D0%B5%D1%87%D0%B0%D1%8E%D1%89%D0%B8%D0%B5%D1%81%D1%8F%D0%BA%D0%B5%D0%B9%D1%81%D1%8B%D0%B8%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%D0%BF%D0%BE%D0%B8%D1%85%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8)

https://github.com/KristinaKac/meetup_2/blob/fb63bf38da7be6b2f7eabf86d32f81b48ab344c0/src/app/modules/meetup/components/meetup/meetup.component.ts#L38
https://github.com/KristinaKac/meetup_2/blob/fb63bf38da7be6b2f7eabf86d32f81b48ab344c0/src/app/modules/user/components/user-form/user-form.component.ts#L23
https://github.com/KristinaKac/meetup_2/blob/fb63bf38da7be6b2f7eabf86d32f81b48ab344c0/src/app/modules/user/components/user-table-row/user-table-row.component.ts#L26

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/e0e6d216bc8d895997c8ccfb1434b663c6de6b0b
