### ISSUE TITLE
Исправить названия 

### ISSUE THREAD

**Issue by annzolotareva** [KristinaKac/meetup_2#3]
Исправить названия интерфейсов стейтов, чтобы по названию было понятно, стейт чего имеется в виду. Аналогично поправить и другие названия, которые используются в Store. Например, эффект "getAll$" можно назвать getAllMeetups$
https://github.com/KristinaKac/meetup_2/blob/fb63bf38da7be6b2f7eabf86d32f81b48ab344c0/src/app/modules/meetup/store/meetup.state.ts#L3

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/22f1fdf8c0050f783dc0d1bd024d3019685d2c4f
