### ISSUE TITLE
Отсутствие отписки от Observable

### ISSUE THREAD

**Issue by annzolotareva** [KristinaKac/meetup_2#6]
https://github.com/KristinaKac/meetup_2/blob/fb63bf38da7be6b2f7eabf86d32f81b48ab344c0/src/app/modules/meetup/components/filter-form/filter-form.component.ts#L42

https://github.com/KristinaKac/meetup_2/blob/fb63bf38da7be6b2f7eabf86d32f81b48ab344c0/src/app/modules/user/components/user-form/user-form.component.ts#L32

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/4a63e6f2c3fbe99c43d67219eaa4d39ae2932588
