### ISSUE TITLE
Можно использовать stringify и transformer

### ISSUE THREAD

**Issue by Anna-Prokhorova** [KristinaKac/meetup_2#7]
Попробуем углубить наши знания Prizm чтобы избавиться от switch-case здесь.
У Призмы для селектов есть возможность инпут параметрами передать ф-ции stringify и transformer.
Они вместе дают возможность в селект передавать массив объектов например.

- stringify будет применяться для отображения айтемов в списке, то есть принимая объект должна отдавать строку которая будет отображаться в опциях селекта

- transformer отвечает за преобразование перед тем как контрол отдаст значение в поток valueChanges, то есть получая объект она должна отдавать то, что мы по итогу отправим на бэк или как у тебя эммитить наверх.

Переприсваивать контролу валью выглядит странно, поэтому предлагаю сделать массив объектов по типу {key: 'name', title: 'По названию'} и скармливать их селекту и двумя вышеупомянутыми функциями заставить это все работать как надо.

https://github.com/KristinaKac/meetup_2/blob/fb63bf38da7be6b2f7eabf86d32f81b48ab344c0/src/app/modules/meetup/components/filter-form/filter-form.component.ts#L45-L62

Подробнее про stringify и transformer можно почитать тут:
stringify: https://prizm.site/components/input-select#stringify
transformer: https://prizm.site/components/input-select#with-transformer

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/81eed5c5d61ad3e640f7a54154c0901e583f3975

**Comment by Anna-Prokhorova** [comment]
Оставила маленький фикс: https://github.com/KristinaKac/meetup_2/commit/81eed5c5d61ad3e640f7a54154c0901e583f3975#r141594095

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/95a3b031fd88c09117491a997d2b3d9e7f0e6cff
