### ISSUE TITLE
В доке призмы не всегда показан best-practice

### ISSUE THREAD

**Issue by Anna-Prokhorova** [KristinaKac/meetup_2#8]
Здесь и во всех аналогичных местах все же лучше вешать класс на див и там указывать эти стили
В доке так сделано по каким-то необъяснимым причинам для которых особо основания если честно нет

Не обязательно даже именно эти стили, можно например сделать лоудер цвета как твой хедер, чтоб еще органичненько смотрелось
https://github.com/KristinaKac/meetup_2/blob/fb63bf38da7be6b2f7eabf86d32f81b48ab344c0/src/app/modules/user/pages/users-page/users-page.component.html#L15

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/1463104c7894fc933cb3161c78951b8b067f7f1e
