### ISSUE TITLE
Некорректная работа поиска

### ISSUE THREAD

**Issue by annzolotareva** [KristinaKac/meetup_2#9]
Поиск работает только если находимся на 1 странице

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/437dd4ba25d5f9744f6424d93b3c06d07cd30f70

**Comment by annzolotareva** [comment]
Есть проблема, если поменять критерий, остаётся результат поиска для прошлого критерия:
![image](https://github.com/KristinaKac/meetup_2/assets/92973848/3602d351-5f4e-4c83-9ebc-350fc8cc2f6a)
Можно при смене критерия выдавать результат для нового критерия в соответствии со старым значением в поле поиска, либо стирать из поля поиска значение для прошлого критерия, сбрасывать результат поиска.

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/fd0d3f7b8684cdb64eb5288bcbf98002c822db23
Результат меняется, в соответствии, со старым значением в поле поиска при переключении критериев, кроме даты, при выборе критерия 'дата' поле очищается.

**Comment by annzolotareva** [comment]
1. Если поставить какой-то критерий, что-то ввести в поле поиска, поставить в критерии "Не выбрано", остается результат для прошлого критерия, даже если полностью стереть значение из поля поиска. Как предложение - сбрасывать результат в таком случае.![photo_2024-05-03_18-37-39](https://github.com/KristinaKac/meetup_2/assets/92973848/b2b71f37-46f2-4a7c-b5e7-dfb082f2f77b)
2. Если мероприятие проведено, то место проведения не отображается, при этом по нему фильтруется. Как предложение - при фильтрации по месту проведения не отображать проведённые мероприятия, либо не скрывать у них места проведения.
![photo_2024-05-03_18-37-39 (2)](https://github.com/KristinaKac/meetup_2/assets/92973848/9e5c281f-6a0c-4082-8505-243a34365beb)

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/16fc8a484a933cdc631ae68762fc55552db35648
1. Фильтр сбрасывается при выборе критерия "не выбрано";
2. Добавлено местоположение у прошедших митапов. Также добавила (закомментировано) вторую реализацию при которой фильтрация происходит только среди митапов, которые еще не прошли.

**Comment by annzolotareva** [comment]
Если выбрать критерий "По дате", ввести значение, выбрать другой критерий, затем снова выбрать "По дате", то значение в поле поиска прежнее, при этом результат сброшен. 
![image](https://github.com/KristinaKac/meetup_2/assets/92973848/1785c0ae-2754-4279-bacb-3c8d2461e5f7)

**Comment by KristinaKac** [comment]
https://github.com/KristinaKac/meetup_2/commit/fa9587fa700aacf160482a6daac481fbc7b95438
